Repository adoptium/installer, pull requests merged in 2020-11, with the labels that each got.

#258 Enable 5 version string components instead of 4
  wix/Build.OpenJDK_generic.cmd
  wix/Includes/OpenJDK.Variables.wxi
Labels: enhancement

#261 Remove unused variables and correct version string variable names
  wix/Build.OpenJDK_generic.cmd
  wix/Includes/OpenJDK.Variables.wxi
Labels: bug, enhancement

#260 Simplify search dir
  wix/Build.OpenJDK_generic.cmd
Labels: bug

#266 Add full version number to PKG metadata
  pkgbuild/OpenJDKPKG.pkgproj.template
  pkgbuild/packagesbuild.sh
Labels: bug

#257 Move quotes around SIGN_CERT into variable itself
  pkgbuild/create-installer-mac.sh
  pkgbuild/packagesbuild.sh
Labels: bug

#268 add macOS testing
  .github/workflows/pgkbuild.yml
Labels: enhancement
